### ISSUE TITLE
Escape remote data

### ISSUE THREAD

**Issue by wresuolc** [mozilla/voicefill#111]
from ace-team:  In https://github.com/mozilla/speaktome/blob/master/extension/content.js#L170
you are injecting HTML that contains remote data, please make sure to
escape the remote data

**Comment by andrenatal** [comment]
ccing @jvehent and @g-k

**Comment by andrenatal** [comment]
What should I escape here? Just single and double quotes?

**Comment by g-k** [comment]
Depends on [the context](https://www.owasp.org/index.php/XSS_(Cross_Site_Scripting)_Prevention_Cheat_Sheet#Output_Encoding_Rules_Summary) you're writing to.

I'd recommend using a well tested template language or https://github.com/cure53/DOMPurify/

**Comment by andrenatal** [comment]
@g-k thanks for the recommendation. Is this enough: https://github.com/mozilla/speaktome/pull/132 ?

**Comment by g-k** [comment]
👍 looks good! 

If you know anything more about the data like `item.confidence` should be numeric or `item.text` should be alphanumeric or never include html tags then it'd be good to lock it down further.

If the data isn't valid then don't display anything or display an error and if tags aren't allowed [call DOMPurify.sanitize without allowed tags]( https://github.com/cure53/DOMPurify/#can-i-configure-it) i.e. `DOMPurify.sanitize(dirty, {ALLOWED_TAGS: []})`

**Comment by andrenatal** [comment]
That's great, thanks @g-k. I won't close this but move to stretch then.

**Comment by mrstegeman** [comment]
Closing this. Things seem to be escaped properly now.
