### ISSUE TITLE
Install bodymovin and webrtc_vad via npm?

### ISSUE THREAD

**Issue by pdehaan** [mozilla/voicefill#114]
Similar to how we're currently integrating [testpilot-ga](https://github.com/mozilla/speaktome/blob/51fbf8fd6a2875c94b0d5672bc6087c2f1238758/package.json#L20-L22):

```js
  "dependencies": {
    "testpilot-ga": "latest"
  },
```

Copy-pasting 3rd party source code into a repo always makes me nervous because you'll never get upstream changes and you're never sure if the code has been modified or tampered. It'd be much nicer to use [npm](https://www.npmjs.com/package/bodymovin) and live with a minor build step. It took a bit of poking and searching of the code to find out exactly what version of the library we had installed.

I'm not even sure what the copy of [/extension/webrtc_vad.js](https://github.com/mozilla/speaktome/blob/51fbf8fd6a2875c94b0d5672bc6087c2f1238758/extension/webrtc_vad.js) we have is. I don't see any copyright headers, version numbers, any idea if it's a Mozilla property or what the code license is. If it's just this, https://github.com/mozilla/webrtcvad_js, not sure if we want to try convincing them to publish that to npm so we can share it more easily. Similarly, we could try setting that repository as a dependency and installing through Git+npm, but that carries a host of dangers like lack of semver and potentially breaking changes at any given time, etc.

**Comment by pdehaan** [comment]
Added package.json to **mozilla/webrtcvad_js** repo in https://github.com/mozilla/webrtcvad_js/pull/2 PR.
That should allow us to `npm install` directly from the GitHub repo, or via npm (if we decide to publish it).

**Comment by andrenatal** [comment]
@pdehaan I merged your PR and published the module to npm, so now is just matter of changing the extension building system to move the module to the right places I guess.
