### ISSUE TITLE
Multiple answers drop down length is inconsistent while zooming in/out

### ISSUE THREAD

**Issue by SoftVision-CarmenFat** [mozilla/voicefill#129]
[Affected versions]:
- Release 54.0.1 and up

[Affected Platforms]:
- All Windows
- All Linux
- All Mac

[Prerequisites]:
- Have a Firefox profile with the latest Voice Fill version 1.2.8 installed.
- Tools -> Page Info -> Permissions -> "Use Default" is unchecked and "Allow" is checked.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites and navigate to www.google.com
2. Click on the microphone button.
3. Say a long sentence.
4. Zoom in and out after the multiple answers are displayed.
5. Observe the way the multiple answers input and drop down list are behaving.

[Expected result]:
- Multiple answers input and drop down list are both rendering properly.

[Actual result]:
- Drop down's length wrongly expands while zooming in and shrinks while zooming out.

[Notes]:
- The issue is more visible if a long sentence was recorded; if there is only a short word, the user has to zoom in more to encounter the issue:
![zooming multipple answers](https://user-images.githubusercontent.com/26000308/28724416-9775220c-73c2-11e7-9aa4-fa8d71804e74.png)

-  This is reproducible using the keyboard shortcut (CTRL & +/-), the mouse (CTRL + scrolling mouse's wheel) and the hamburger menu (+ and - buttons). 
- This is reproducible on all supported websites.
- Added a screen cast with the issue:

![drop down](https://user-images.githubusercontent.com/26000308/28724425-a04ba7ac-73c2-11e7-8798-5c3bf90c0467.gif)

**Comment by johngruen** [comment]
Not sure how we'd fix this
