### ISSUE TITLE
The microphone button remains in hover state after clicking it if the microphone permission was previously denied

### ISSUE THREAD

**Issue by SoftVision-CarmenFat** [mozilla/voicefill#170]
[Affected versions]:
- Firefox 55.0.2 and up
- Voice Fill 1.3.0

[Affected Platforms]:
- All Windows
- All Linux

[Prerequisites]:
- Latest Voice Fill add-on (1.3.0) was previously installed on a clean profile.
- Tools -> Page Info -> Permissions -> Use the Microphone -> "Use Default" is unchecked and "Block" is checked.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites and navigate to a supported website.
2. Click on the microphone button from the right side of the search input.
3. Wait for the overlay to be dismissed and observe the microphone button.

[Expected result]:
- The microphone button has a light turquoise background.  

[Actual result]:
- The microphone button has a darker turquoise background.

[Notes]:
- Clicking anywhere on the page dismisses the microphone button hover state;
- Please see the screen cast attached:  

![hover state](https://user-images.githubusercontent.com/26000308/29558517-f7a552f2-8734-11e7-8305-9b495af3c99d.gif)

**Comment by andrenatal** [comment]
@SoftVision-CarmenFat I couldn't reproduce this error, please see the attached screencast. 

Could you please try again a couple of times with the latest version from Test Pilot and reopen this if still happens?

![screen_cast_stm](https://user-images.githubusercontent.com/973388/30413344-4badfe04-98d2-11e7-8c4b-08055fe594fb.gif)

**Comment by SoftVision-CarmenFat** [comment]
Hi @andrenatal 
As I mentioned in the description, the platforms where this issue can be reproduced are Windows and Linux. From your attached screencast, I can notice that you used Mac OS.

I double checked this and it still reproduces, with both Test Pilot version and custom repo built today 9/14/2017.

**Comment by andrenatal** [comment]
Fix on:
- [x] Mac
- [ ] Windows
- [ ] Linux
