### ISSUE TITLE
Cannot initialize a voice search after microphone "Don't Allow" permission is cleared

### ISSUE THREAD

**Issue by Softvision-CristinaBadescu** [mozilla/voicefill#184]
[Affected versions]:
- Firefox 55.0.3 and up
- Voice Fill 1.3.0

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Latest Voice Fill add-on (1.3.0) was previously installed on a clean profile.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites and navigate to www.google.com.
2. Click on the "Microphone" button from the right side of the search field and click "Don't Allow" on the "Microphone to share" doorhanger.
3. Set the page with the following permission: "Use the Microphone" unchecked and "Allow" checked in Tools>Page Info>Permissions tab.
4. Click on the "Microphone" button from the right side of the search field and observe the behavior.

[Expected result]:
- The voice search is initialized.

[Actual result]:
- An overlay with the message "Sorry we encountered an error" appears.

[Notes]:
- Here is a screen recording with the issue: https://goo.gl/8DVRN2

**Comment by mrstegeman** [comment]
Cannot reproduce.
