### ISSUE TITLE
Voice Fill is unable to record on the Unbranded Firefox Release using Windows

### ISSUE THREAD

**Issue by SoftVision-CarmenFat** [mozilla/voicefill#201]
[Affected versions]:
- Unbranded Firefox 55.0.3 (64-bit) and 55.0.4 (64-bit)

[Affected Platforms]:
- All Windows

[Prerequisites]:
- Pre-release Voice Fill v. 1.3.0 was previously installed on a clean profile.
- Tools -> Page Info -> Permissions -> Use the Microphone -> "Use Default" is unchecked and "Allow" is checked.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites and navigate to any supported website.
2. Click on the microphone button and say something.
3. Observe what happens next.

[Expected result]:
-  The recording process starts and the recording waves circles are displayed while talking.

[Actual result]:
- The recording process doesn't start, no recording waves circles are displayed while talking.

**Comment by mrstegeman** [comment]
Cannot reproduce.
