### ISSUE TITLE
Voice Fill overlay is dismissed if the browser is resized while on Google domains

### ISSUE THREAD

**Issue by SoftVision-CarmenFat** [mozilla/voicefill#204]
[Affected versions]:
- Firefox 55.0.3 and up
- Voice Fill 1.3.1

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Latest Voice Fill add-on 1.3.1 (custom repo built on 9/19/2017) was previously installed on a clean profile.
- Tools -> Page Info -> Permissions -> Use the Microphone -> "Use Default" is unchecked and "Allow" is checked.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites and navigate to a Google supported website.
2. Click on the microphone button.
3. Resize the browser (click on the browser's "Resize" button).
4. Observe Voice Fill's overlay behavior.

[Expected result]:
- The Voice Fill overlay correctly renders with the new size of the browser and the session is not interrupted.

[Actual result]:
- Voice Fill overlay is dismissed.

[Notes]:
- This affects only the Google domains - tested with: 
https://www.google.com/ 
https://www.google.it/  
https://www.google.de/ 
https://www.google.ae/
- Attaching a screen recording of the issue:

![resize](https://user-images.githubusercontent.com/26000308/30597041-7809e090-9d5e-11e7-9bcd-42b7dbdf423a.gif)

**Comment by SoftVision-CarmenFat** [comment]
I've noticed that this behavior is also reproducible when opening the "Inspector" either through **context menu** or **hamburger menu** (Web Developer). Still, only Google websites are affected by this action.

**Comment by mrstegeman** [comment]
Cannot reproduce.
