### ISSUE TITLE
"Please enable your microphone to use Voice Fill" message is wrongly displayed after performing multiple voice searches using toolbar's button

### ISSUE THREAD

**Issue by Softvision-CristinaBadescu** [mozilla/voicefill#236]
[Affected versions]:
- Firefox 56.0.2 and up
- Voice Fill v.1.3.4.1

[Affected Platforms]:
- All Windows
- All Linux
- All Mac

[Prerequisites]:
- Have a Firefox profile with the Voice Fill (v. 1.3.4.1) experiment installed.
- Tools -> Permissions -> "Use default" is unchecked and "Allow" is checked.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites.
2. Click the Voice Fill button from the toolbar at least 5 times.
3. Go to the last opened tab and observe the behavior.

[Expected result]:
- The recording session starts.

[Actual result]:
- The "Please enable your microphone to use Voice Fill" message is displayed.

[Notes]:
- The frequency of encountering this issue may vary: 4 or 6 voice searches.
- This issue is also reproducible when using the "Voice Fill" button located in the right side of the search bar.
- This issue is also reproducible if you manually click "Allow" microphone permission for each search.
- Here is a screen recording of the issue:
![voice searches 5 times](https://user-images.githubusercontent.com/31244235/32444818-8d02085a-c30c-11e7-94fc-b2dccd5291ac.gif)

**Comment by mrstegeman** [comment]
Cannot reproduce.
