### ISSUE TITLE
Support for other languages

### ISSUE THREAD

**Issue by Thaodan** [mozilla/voicefill#248]
Would it be possible to implement this?

**Comment by DavidLibeau** [comment]
Like this line is showing https://github.com/mozilla/speaktome/blob/master/extension/content.js#L679, languages is supposed to be supported, but with a test with french language, it does not seems to work (or maybe I enter the wrong language code).

Can we have more info on that?

**Comment by andrenatal** [comment]
Hello @Thaodan and @DavidLibeau . This is being worked out here: https://github.com/mozilla/speaktome/pull/275

We expect to ship the updated version by the end of this week. We'll let you know when we do it.

Thanks!

**Comment by mrstegeman** [comment]
Release in 1.4.3
