### ISSUE TITLE
 Firefox Voice Fill is slow

### ISSUE THREAD

**Issue by urzds** [mozilla/voicefill#251]
Firefox Voice Fill takes a long time from "Listening ..." to "Processing ...", after I stop talking. This makes it feel less useful and slower than typing. Maybe a command word (like "Go!") to end the "Listening ..." stage would help?

See-Also: mozilla/testpilot#3331

**Comment by Softvision-CristinaBadescu** [comment]
Can you please specify how long did you wait? The transition from "Listening" to "Processing" overlay should last only some seconds (3-6 second at top). 

Also, please do mention on what operating system have you encountered this issue and what Firefox version you have used.

**Comment by urzds** [comment]
Firefox 58.0.1 on Linux (KDE neon User LTS 5.12, based on Ubuntu LTS 16.04).

> Can you please specify how long did you wait? The transition from "Listening" to "Processing" overlay should last only some seconds (3-6 second at top).

That is about right. For me that feels (or actually is?) longer than I'd need to type the phrase. Hence the benefit of using this appears smaller than it could.

**Comment by Softvision-CristinaBadescu** [comment]
@andrenatal, do you think it is possible to improve the transition time from "Listening" to "Processing" overlay?
