### ISSUE TITLE
"block new requests asking for mic" breaks voice fill

### ISSUE THREAD

**Issue by JustinScott** [mozilla/voicefill#261]
I had the block new requests box checked, so I manually allowed duckduckgo to use the mic in page info -> permissions, and voice fill would not work. It kept saying "enable mic to use voice fill". I unchecked that box, and voice fill works now. It didn't request any new permission, and I didn't change anything besides unchecking that option.

**Comment by Softvision-CristinaBadescu** [comment]
Hello,

I've tested this issue and managed to reproduce it using Voice Fill v1.3.8 (custom built on 2018-03-29), on latest Nightly build 61.0a1 (2018-03-28), on Windows 10 x64.

I've enabled the "Block new requests asking to access your microphone" option from "about:preferences#privacy" ->Permissions -> Microphone, navigated to DuckDuckGo page and could not perform a voice search. After unchecking this option, I could use Voice Fill on https://duckduckgo.com/ without any problems. 

@andrenatal , can you please take a look and see if there is something we can do about this?

**Comment by mrstegeman** [comment]
Cannot reproduce.
