### ISSUE TITLE
Microphone button is wrongly displayed outside the search input on Nightly

### ISSUE THREAD

**Issue by SoftVision-CarmenFat** [mozilla/voicefill#34]
[Affected versions]:
- Nightly 56.0a1

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Have a Firefox profile with the latest Voice Fill version (1.0 -dev, built on 05/07/2017) installed.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites.
2. Navigate to https://duckduckgo.com/
3. Observe the way the microphone button is displayed.

[Expected result]:
- The microphone button is displayed inside the search input.

[Actual results]:
- The microphone button is displayed outside the search input, in different places of the website's content area.

[Notes]:
- On http://www.ebay.com/ the microphone button is not visible nor reachable because the website's notification overlaps it.
- This is also reproducible on the following websites: 
1. http://www.bing.com/ - microphone button is displayed on the bottom left of the screen
2. https://www.google.com - microphone button is displayed on the top left of the screen
3. https://www.apple.com/ - microphone button is displayed on the bottom left of the screen
- Here is a screen recording with the issue:

![nightly](https://user-images.githubusercontent.com/26000308/27871641-ed3bb3ca-61ae-11e7-8073-45809e3d7dca.gif)

**Comment by clouserw** [comment]
This is not a launch feature.  For launch, we are only targeting about:home, about:newtab, and context menus.

**Comment by mrstegeman** [comment]
This no longer seems to be an issue.
